Migrations
IAlmostDeveloper/xsolla-garage-backend pull request #7
Opened 2020-09-11 13:32 UTC by rdsalakhov

2020-09-14 03:44 UTC, IAlmostDeveloper requested changes

2020-09-14 03:44 UTC, IAlmostDeveloper commented on src/main.go
> +	}()
Пока вынес миграцию в горутину, которая пробует подключиться к БД каждые 5 секунд.

2020-09-14 03:44 UTC, IAlmostDeveloper commented on migrations/00001_initial_migration.sql
>  USE XsollaGarage;
Сюда можно добавить создание базы данных XsollaGarage? Ее пока что по прежнему надо создавать руками.

2020-09-14 09:48 UTC, rdsalakhov commented on src/main.go
> +	}()
Мне кажется это надо решать как-то через порядок запуска контейнеров. Или закостылить через restart:always в композе:
`
garage-backend:
    container_name: garage-backend
    image: ialmostdeveloper/xsolla-garage-backend
    ports:
      - 8081:8081
    restart: always
`

2020-09-14 09:50 UTC, rdsalakhov commented on migrations/00001_initial_migration.sql
>  USE XsollaGarage;
Это странно, она же должна создаваться через эту переменную в композе: `- MYSQL_DATABASE=XsollaGarage`

2020-09-15 03:51 UTC, IAlmostDeveloper commented on migrations/00001_initial_migration.sql
>  USE XsollaGarage;
Выдается ошибка
 error: unknown database "XsollaGarage"
![image](https://user-images.githubusercontent.com/51601917/93163436-22cc9d00-f6e5-11ea-8d40-b6807865d988.png)

2020-09-15 04:40 UTC, IAlmostDeveloper commented on src/main.go
> +	}()
Да, пусть так

2020-09-15 04:41 UTC, merged